name: catsketball
channels:
    - defaults
    - conda-forge
dependencies:
    - pandas
    - streamlit
    - pip
    - colour
    - pyyaml
    - scikit-learn
    - scipy
    - pip:
        - espn_api

